### ISSUE TITLE
The display doesn't show hashing speed

### ISSUE THREAD

**Issue by matssjodin** [KnCMiner/images#1]
After upgrading my Neptune to 1.06 the internal display does not show any hashing speed at all. Only flipping back and forth from IP-address and an empty MH/s screen.

**Comment by dvitas** [comment]
Does it happen when using BFGMiner? If so, I think I know what might be the problem then...

**Comment by matssjodin** [comment]
Yes. I am using BFGMiner.

**Comment by dvitas** [comment]
Please, try this hotfix:
https://github.com/KnCMiner/images/releases/untagged-637eb105f90931263023
Go to the "Upgrade" page, select this file as "Firmware Upgrade" and upload it. After successful upload, do not reboot! Instead, on the next page press "Go Back"!
Does it solve the issue?
It is only runtime fix, it will go away after reboot. If it works, I will create a new binary upgrade image with permanent fix.

**Comment by matssjodin** [comment]
I can't download that image. I get a 404 trying to access it.

**Comment by dvitas** [comment]
Try this link:
https://drive.google.com/file/d/0B-wTUcz-2xXpSGtEMUkzaVQyZDg/view?usp=sharing

**Comment by matssjodin** [comment]
Yes, it works! Displaying hashing speed now.

**Comment by dvitas** [comment]
Good. Thanks a lot for reporting the problem!
Proper upgrade image: https://github.com/KnCMiner/images/blob/master/Neptune/neptune-1.06s.bin
